name: CI/CD
on: [push, pull_request]
jobs:
    test:
        strategy:
            matrix:
                os: [ubuntu-20.04, macos-10.15]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: 'recursive'
            - name: Setup CMake
              uses: jwlawson/actions-setup-cmake@v1.5
              with:
                  cmake-version: '3.18.x'
            - name: Check CMake version
              run: cmake --version
            - name: Install
              run: |
                  mkdir build
                  pushd build
                  cmake ..
                  make
                  popd
            - name: Check tests
              run: |
                  pushd build/tests
                  ./tests_main --list-tests
                  popd